---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Ensure Redis Configuration
  template: 
    src: redis.conf.j2 
    dest: /etc/redis/redis.conf 
    owner: redis
    group: redis 
    mode: 0644
  notify: [ "redis_restart" ]